// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

export function problem_002() {
  const target = 4000000;
  
  let fibb_last = 0;
  let fibb_next = 1;
  
  let sum = 0;
  while(fibb_next < target) {
    [fibb_last, fibb_next] = [fibb_next, fibb_last + fibb_next];

    if(fibb_last % 2 === 0) {
      sum += fibb_last;
    }
  }
  return sum;
}